branch:
    only:
    - "master"
language: go
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libopenal-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev xorg-dev libgl1-mesa-dev xvfb
go:
- 1.6.2
script:
    - Xvfb :10 -ac &
    - export DISPLAY=:10
    - go run main.go

