sudo: false
addons:
  apt_packages:
    - libgl1-mesa-dev
    - xorg-dev
language: go
go:
  - 1.6.2
install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).
script:
  - go get -t -v ./...
  - go run main.go
